.travis.yml, package.json, src/swap.flows/BTC2ETH.js, src/swap.flows/BTC2ETHTOKEN.js, src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js, src/swap.swaps/BtcSwap.js, src/swap.swaps/EthSwap.js, src/swap.swaps/EthTokenSwap.js
!! NOW public methods on Flow throw ERROR if called TOO EARLY
=> + flows: extra checks and communication

package.json, src/swap.flows/BTC2ETH.js, src/swap.flows/BTC2ETHTOKEN.js, src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js, src/swap.swap/Flow.js, src/swap.swap/Room.js, src/swap.swap/Swap.js, src/swap.swaps/EthSwap.js
Extra messaging to prevent deadlock on signing step
=> * flow: secure steps

package.json
=> Build vanilla under Windows

src/swap.orders/Order.js, src/swap.swap/Swap.js
=> x fix wrong participant

package.json
=> build version 0.2.2

src/swap.swaps/BtcSwap.js, src/swap.swaps/EthSwap.js, src/swap.swaps/EthTokenSwap.js
usually tx takes 50 000, so 100k is enough
=> ethtokenswap: update gas limit to 100 000

src/swap.app/SwapApp.js, src/swap.flows/BTC2EOS.js, src/swap.flows/BTC2ETH.js, src/swap.flows/BTC2ETHTOKEN.js, src/swap.flows/EOS2BTC.js, src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js, src/swap.flows/ETHTOKEN2USDT.js, src/swap.flows/USDT2ETHTOKEN.js, src/swap.orders/SwapOrders.js, webpack.config.babel.js
Fix build UMD on Windows OS
Support tokens with decimals in name
Return new order data on create
=> Windows build + tokens with decimals + new order data

src/swap.auth/btc.js, src/swap.auth/ltc.js
ltc.js account overrides btc.account if uses __proto__
=> fix account problem

__mocks__/swap.app.js, src/swap.flows/BTC2EOS.js, src/swap.flows/EOS2BTC.js, src/swap.swaps/EosSwap.js, tests/EOSBTC.test.js
=> EOS update

package.json
=> update: 0.2.3 build 2

package.json, src/swap.app/Events.js, src/swap.room/SwapRoom.js, src/swap.swap/Room.js
=> reduce console.log output

.npmignore, package.json
- don't commit simple dir, its another package
- destination address
=> npm version 0.2.3 build 8

src/swap.swaps/EthSwap.js, src/swap.swaps/EthTokenSwap.js
Более аккуратно работает с ошибками.
=> swaps: checkSwapExists handles errors

package.json
Changes from 0.2.3:
- set destination address (even at runtime)
- fund script from external wallet
- new tokens
- bug fixes
- ? @noxonsu 
Coming up in 0.3.1:
- a bundle to easily include swap.core into your project
- support for DEBUG=swap:* logs grouping
- partial orders and requests
- probably will remove SwapApp singleton
- REPL for your unfinished swaps (simple/examples/repl.js)
- autorefund module
- working jest tests
`master` will be breaking while developing 0.3.1, so please stay at 0.3.0 release
=> release 0.3.0

simple/package.json, simple/src/helpers/history.js, simple/src/helpers/orders.js, simple/src/helpers/swap.js, simple/src/instances/bitcoin.js, simple/src/instances/ethereum.js, simple/src/wallet/index.js, simple/tests/SwapWallet.test.js
=> Simple 0.3.1

src/swap.flows/ETHTOKEN2BTC.js, src/swap.swaps/EthTokenSwap.js
({ spender }) instead of (spender)
=> [NO TEST] ethTokenSwap: method checkAllowance receives object, not address

src/swap.flows/ETH2BTC.js
=> Typeenterfix

simple/examples/listFinished.js, simple/src/helpers/history.js
=> simple: import env.storage from swapApp, not swap.core

__mocks__/swap.app.js, src/swap.flows/BTC2ETH.js, src/swap.flows/BTC2ETHTOKEN.js, src/swap.swaps/EthSwap.js, src/swap.swaps/EthTokenSwap.js
=> flow: compare secretHash to stored in contract before withdraw (ETH, ERC20)

simple/src/config/getConfig.js
=> simple: import directly from swap.* packages, not swap.core

src/swap.orders/Order.js
https://github.com/swaponline/swap.react/issues/1287
=> order: declineRequest duplicated requests when called without args

__mocks__/swap.app.js, simple/package.json, simple/src/config/getConfig.js, src/swap.app/constants/ENV.js, src/swap.app/util/actualKey.js
=> util: actualKey depends on sessionStorage

package.json
На пуллах в кор при изменении функциональности, в конце пулла прогнать:
```bash
npm version patch
```
или
```bash
npm version minor
```
Подробнее, про версии тут https://semver.org
=> use npm version for builds

src/swap.flows/BTC2ETH.js, src/swap.flows/BTC2ETHTOKEN.js, src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js
tryWithdraw нужен, если у тебя все пошло не так, но ты знаешь секрет
Начать своп, на второй стороне заблокировать деньги, скопировать секрет
На второй стороне не отправлять деньги, а просто украсть секрет
=> ETHTOKEN2BTC: tryWithdraw didn't withdraw anything

simple/src/instances/bitcoin.js, src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js, src/swap.swaps/BtcSwap.js, tests/btcSwap.test.js
Expected confidence now should be at least 80%. That's OK, because you will spend money from script to your wallet with a high fee, so you will raise the chance TX will be mined
0.8 достаточно, потому что ты все равно потратишь деньги с контракта на свой кошелек, и можешь поставить любую комиссию, и сделать вероятность майнинга выше.
=> BtcSwap: calculate confident script balance

src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js, src/swap.swaps/EthSwap.js, src/swap.swaps/EthTokenSwap.js
=> ETH2BTC: stop fetching secret after success

simple/examples/package-lock.json, simple/examples/package.json
Это скорее всего не поможет, потому что алерт внутри ipfs
=> simple/examples: update deps

src/swap.app/constants/index.js, src/swap.orders/SwapOrders.js
=> orders: fix rounding errors

package-lock.json, package.json, simple/package-lock.json, simple/package.json
=> Release 0.3.2

simple/src/instances/ethereum.js
```
WEB3_MAINNET_PROVIDER=https://infura.io...
```
=> simple: set ETH provider from env config

package-lock.json, package.json, simple/package-lock.json, simple/package.json
=> Release 0.3.3

src/swap.app/util/helpers.js, src/swap.flows/BTC2ETH.js, src/swap.flows/BTC2ETHTOKEN.js
=> BTC2XXX: allow unconfirmed balance from outside script

src/swap.flows/BTC2ETHTOKEN.js, src/swap.swaps/EthSwap.js, src/swap.swaps/EthTokenSwap.js
Исправил функцию в токенах и эфирах
=> Не работает завершение свапа второй стороной (withdrawNoMoney)

src/swap.flows/ETHTOKEN2USDT.js, src/swap.flows/USDT2ETHTOKEN.js, src/swap.swaps/UsdtSwap.js
=> USDT: fix tryRefund and tryWithdraw

src/swap.flows/BTC2ETHTOKEN.js, src/swap.flows/USDT2ETHTOKEN.js, src/swap.swaps/EthTokenSwap.js
Решение проблемы https://github.com/swaponline/swap.core/issues/351
=> проверка на подмену токенов

src/swap.orders/Pair.js, src/swap.swaps/EthTokenSwap.js
=> Нулевые decimals у токенов, фикс проверки баланса токенов в контракте (decimals)

src/swap.app/util/erc20.js, src/swap.app/util/index.js, src/swap.app/util/typeforce.js
Решение проблемы https://github.com/swaponline/swap.react/issues/1868
также добавил функцию, для регистрации новых токенов в коре
=> erc20 utils - коректный isCoinAddress, isPublicKey + функция добавления токена в кор на лету

src/swap.app/constants/COINS.js, src/swap.app/constants/COINS_PRECISION.js, src/swap.app/util/typeforce.js
`^[A-Za-z0-9:]{26,54}$` for
- `bitcoincash:qqrxa0h9jqnc7v4wmj9ysetsp3y7w9l36u8gnnjulq` - length 54
- `bchtest:pq7mwz272zc44rtw9qdcak55l82rrtu38gekt9zpmt` - length 50
=> swap.app: add new coin (BCH)

src/swap.swaps/BtcSwap.js
Reverts swaponline/swap.core#371
=> Revert "BtcSwap: fix dynamic fee"

simple/src/helpers/request.js, simple/src/instances/bitcoin.js, simple/src/instances/ethereum.js
Добавил обертку для request с поддержкой кеширования и последовательных запросов
Добавил кеширование в btc при обращении к апи (запрос актуальной комиссии, баланс, проверка тх)
Добавил кеширование в eth при обращении к апи (запрос баланса токенов, информация об актуальной комиссии)
=> Simple - кеширование запросов к апи

src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js
Решение проблемы
https://github.com/swaponline/swap.react/issues/2028
Так-же это относится к рефандам в ETH2BTC
=> fix refund (eth,token) btc . возврашало Promise, а нужен был результат

src/swap.swaps/EthSwap.js, src/swap.swaps/EthTokenSwap.js
Ишью https://github.com/swaponline/swap.core/issues/358
=> Код EthTokenSwap соответствует коду EthSwap

.travis.yml
=> .travis.yml: fix nodejs version to 11

src/swap.flows/BTC2ETH.js, src/swap.flows/BTC2ETHTOKEN.js
=> swap.flows: add skipSyncBalance method to btc2eth/token

src/swap.orders/Order.js
Решение ишью для реакта https://github.com/swaponline/swap.react/issues/2091
Не работал альтернативный адрес при partial запросе
=> partial orders destination address fix

src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js, src/swap.swaps/BtcSwap.js
Решение ишью https://github.com/swaponline/swap.core/issues/459
=> Known tx not always is error

src/swap.swaps/BtcSwap.js
Решение ишью https://github.com/swaponline/swap.core/issues/453
=> check secret size in btc script

src/swap.app/util/erc20.js
=> Fix erc20register

src/swap.flows/BTC2ETH.js, src/swap.flows/BTC2ETHTOKEN.js, src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js, src/swap.swaps/BtcSwap.js
Поченил свапы BTC-ETH и BTC-ERC20
Так-же отдельно требуется обновить BCH и LTC свапы
=> Fix btc swaps

package.json, simple/package.json
=> update depency + version level up

package.json, simple/package.json, src/swap.flows/ETH2BTC.js, src/swap.flows/ETH2GHOST.js, src/swap.flows/ETHTOKEN2BTC.js, src/swap.flows/ETHTOKEN2GHOST.js, src/swap.flows/GHOST2BTC.js
Функция проверки, произвела ли вторая сторона рефайнд BTC
=> check  - other side do refund

src/swap.swaps/GhostSwap.js
Fix refund Ghost
Example of refund transaction:
https://ghostscan.io/tx/0d0bbb69d50792001ec77ca85b44e9192bffff9bcce502315f9e9702af528d3b
=> fix refund ghost

src/swap.app/SwapApp.js, src/swap.flows/ETH2BTC.js, src/swap.flows/ETHTOKEN2BTC.js, src/swap.swaps/BtcSwap.js
https://github.com/swaponline/Marketmaker/issues/4
=> whiltelist btc (не ждать подтверждения от доверенных продавцов)
